---
timezone: Europe/Sofia
server_hostname: rpi4

data_dir: /mnt/data
apps_dir: "{{ data_dir }}/apps"
backups_dir: "{{ data_dir }}/backups"
user_home_dir: "/home/{{ ansible_user }}"

mealie_dir: "{{ apps_dir }}/mealie"
mealie_port: "9925"

forgejo_dir: "{{ apps_dir }}/forgejo"
forgejo_port: "3000"

kopeika_dir: "{{ apps_dir }}/kopeika"
kopeika_port: "8091"

ansible_become: true
ansible_become_method: sudo
ansible_become_pass: "{{ vault_become_password }}"
