---
- name: Create backup script directory
  ansible.builtin.file:
    path: "{{ backup_script_dir }}"
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Install shared backup library
  ansible.builtin.copy:
    src: lib.sh
    dest: "{{ backup_script_dir }}/lib.sh"
    mode: "0755"
    owner: root
    group: root

- name: Set up pihole backup
  ansible.builtin.import_tasks: pihole.yml

- name: Set up mealie backup
  ansible.builtin.import_tasks: mealie.yml
