---
- name: Restart journald
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted

- name: Reload ssh
  ansible.builtin.systemd:
    name: ssh
    state: reloaded

- name: Restart rpi-firewall
  ansible.builtin.systemd:
    name: rpi-firewall
    state: restarted
  when: not ansible_check_mode
